//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuzuMarker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4294934451")]
        public uint CustomCleaningStrokeColor {
            get {
                return ((uint)(this["CustomCleaningStrokeColor"]));
            }
            set {
                this["CustomCleaningStrokeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4289525422")]
        public uint NormalCleaningStrokeColor {
            get {
                return ((uint)(this["NormalCleaningStrokeColor"]));
            }
            set {
                this["NormalCleaningStrokeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2147450803")]
        public uint CustomCleaningFillColor {
            get {
                return ((uint)(this["CustomCleaningFillColor"]));
            }
            set {
                this["CustomCleaningFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2142041774")]
        public uint NormalCleaningFillColor {
            get {
                return ((uint)(this["NormalCleaningFillColor"]));
            }
            set {
                this["NormalCleaningFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint PhotoshopBridgeType {
            get {
                return ((uint)(this["PhotoshopBridgeType"]));
            }
            set {
                this["PhotoshopBridgeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4016")]
        public int PhotoshopExtensionHTTPServerPort {
            get {
                return ((int)(this["PhotoshopExtensionHTTPServerPort"]));
            }
            set {
                this["PhotoshopExtensionHTTPServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int UIPolygonStrokeThickness {
            get {
                return ((int)(this["UIPolygonStrokeThickness"]));
            }
            set {
                this["UIPolygonStrokeThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7FE9B2FF")]
        public string LassoModeBackgroundColor {
            get {
                return ((string)(this["LassoModeBackgroundColor"]));
            }
            set {
                this["LassoModeBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFB2F0FF")]
        public string LassoStrokeColor {
            get {
                return ((string)(this["LassoStrokeColor"]));
            }
            set {
                this["LassoStrokeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7FB2F0FF")]
        public string LassoFillColor {
            get {
                return ((string)(this["LassoFillColor"]));
            }
            set {
                this["LassoFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4293951616")]
        public uint FailStatusColor {
            get {
                return ((uint)(this["FailStatusColor"]));
            }
            set {
                this["FailStatusColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4278254234")]
        public uint SuccessStatusColor {
            get {
                return ((uint)(this["SuccessStatusColor"]));
            }
            set {
                this["SuccessStatusColor"] = value;
            }
        }
    }
}
